In [27]:
import numpy as np
import shapley 
import RDG_interventional

f1: xs[0] + np.exp(xs[1] / (2 + xs[4])) + 2*(xs[2] * xs[3]) + np.sin(2*(xs[5] + xs[6]))


f2: 2*(np.sign(xs[0])) + np.sign(xs[1]*xs[2]*xs[3]) + np.sign(xs[4]*xs[5]*xs[6]) 

In [28]:
def f(xs):
    
    if type(xs).__module__ == np.__name__:
        #print(xs.shape)
        xs = xs.reshape(xs.shape[0],xs.shape[1])
        #print(xs.shape)
        #2*(np.sign(xs[0])) + np.sign(xs[1]*xs[2]*xs[3]) + np.sign(xs[4]*xs[5]*xs[6])
        #2*(np.sign(xs[0])) + np.sign(xs[1]*xs[2]*xs[3]) + np.sign(xs[4]*xs[5]*xs[6])
        #i = xs[0] + np.exp(xs[1] / (2 + xs[4])) + 2*(xs[2] * xs[3]) + np.sin(2*(xs[5] + xs[6]))
        #i = (np.sign(xs[:,0])) + (np.sign(xs[:,1]*xs[:,2]*xs[:,3])) + np.sign(xs[:,4]*xs[:,5]*xs[:,6])
        #i = 2*(xs[:,0] * xs[:,2] * xs[:,3]) + 4*(xs[:,4] * xs[:,5]) - 3*(xs[:,1])**2 - (xs[:,6])
        #i = xs[:,0] + xs[:,1] + (xs[:,2])
        #i = xs[:,0] + xs[:,1] + xs[:,2] + (xs[:,0] * xs[:,1] * xs[:,2])
        #i = (xs[:,0] * xs[:,1])/4 + (xs[:,2]/(2+xs[:,3])) 
        i = (np.sign(xs[:,0])) + (np.sign(xs[:,1]*xs[:,2]*xs[:,3]))
        #i = ((xs[:,0])) * xs[:,1] * xs[:,2] * xs[:,3]
        #i = ((xs[:,0])) * xs[:,1] + 2*xs[:,3]
        return(i)
        
        #return ((xs[:,0] and xs[:,4]) or (xs[:,1] or xs[:,2])) + xs[:,3]
        #return xs[:,0] + np.exp(xs[:,1] / (2 + xs[:,4])) + 2*(xs[:,2] * xs[:,3]) + np.sin(xs[:,5] + xs[:,6])
    else:
        #return ((xs[0] and xs[4]) or (xs[1] or xs[2])) + xs[3]
        #return (xs[0] and (xs[1] or xs[2])) or ((xs[3] and not xs[4]) or xs[5])
        #return xs[0] + np.exp(xs[1] / (2 + xs[4])) + 2*(xs[2] * xs[3]) + np.sin(xs[5] + xs[6])
        #i =  xs[0] + np.exp(xs[1] / (2 + xs[4])) + 2*(xs[2] * xs[3]) + np.sin(2*(xs[5] + xs[6]))
    
        #i = (np.sign(xs[0])) + (np.sign(xs[1]*xs[2]*xs[3])) + np.sign(xs[4]*xs[5]*xs[6])
        #i = 2*(xs[0] * xs[2] * xs[3]) + 4*(xs[4] * xs[5]) - 3*(xs[1])**2 - (xs[6])
        #i = xs[0] * 2*xs[1] + (xs[2]/(2+xs[3])) 
        #i = (np.sign(xs[0])) + (np.sign(xs[1]*xs[2]*xs[3]))
        #i = xs[0] + xs[1]+ xs[2]
        #i = xs[0] + xs[1] + xs[2] + (xs[0] * xs[1] * xs[2])
        #i = (xs[0] * xs[1])/4 + (xs[2]/(2+xs[3])) 
        i = (np.sign(xs[0])) + (np.sign(xs[1]*xs[2]*xs[3]))
        #i = ((xs[0])) * xs[1] * xs[2] * xs[3]
        #i = ((xs[0])) * xs[1] + 2*xs[3]
        
        return(i)

In [29]:
#x = [1 for _ in range(0,7)]
x = [np.random.uniform(-1,1) for _ in range(0,7)]

z = [np.random.uniform(-1,1) for _ in range(0,7)]


In [30]:
x = [1,-1,1,1]
z = [0,0,0,0]

#x = [1,1,1]
#z =[0,0,0]

In [31]:
ss_atts,seps,nonseps = RDG_interventional.RDG(f,list(x),list(z),[-1 for _ in range(0,len(x))],[1 for _ in range(0,len((x)))],0.1)
print(ss_atts)

{(0,): array([1])}


In [32]:
s_atts = shapley.shapley_int(f,np.asarray(x),np.asarray(z))
s_atts

{0: array([1.]),
 1: array([-0.33333333]),
 2: array([-0.33333333]),
 3: array([-0.33333333])}

In [33]:
from itertools import permutations
import math
import random

def value_marg(f,S,S_bar,x,z,feature_value):
    xs = list(np.zeros(len(x)))
    if len(S) > 0:
        for i in S:
            xs[i] = x[i]
    if len(S_bar) > 0:
        for i in S_bar:
            xs[i] = z[i]

    with_i = xs.copy()
    with_i[feature_value] = x[feature_value]
    without_i = xs.copy()
    without_i[feature_value] = z[feature_value]
    
    return f(np.asarray(with_i).reshape(1,-1)) - f(np.asarray(without_i).reshape(1,-1))



def shap_taylor(x,z):
    indi_atts = {}
    pair_atts = {}
    
    n = x.shape[0]
    k = 2
    for feature_index in np.arange(x.shape[0]):
        
        with_i = z.copy()
        with_i[feature_index] = x[feature_index]
        without_i = z.copy()

    
        indi_atts[feature_index] = f(np.asarray(with_i).reshape(1,-1)) - f(np.asarray(without_i).reshape(1,-1))
        
        rows = np.arange(x.shape[0])
        columns = rows.copy()
    for feature_index_i in rows:
        columns = np.delete(columns,0)
       
        
        for feature_index_j in columns:
            if feature_index_i != feature_index_j:
                    perms = 0
                    perm_value = 0
                    for i in range(0,5):
                        

                        new_permutations = np.arange(n).copy()
                        new_permutations = np.delete(new_permutations,[feature_index_j,feature_index_i])


                        perms += 1
                  

                        S = random.sample(list(new_permutations), random.randint(1,len(new_permutations)))
                        print(S)


                        without_i = z.copy()
                        for index in S:
                            without_i[index] = x[index]
                        with_i = without_i.copy()
                        with_i[feature_index_j] = x[feature_index_j]
                        with_i[feature_index_i] = x[feature_index_i]

                        t = len(S)
                        
                        coef = (math.factorial(n-1))/((math.factorial(t)*(math.factorial(n-1-t))))
                        perm_value += f(np.asarray(with_i).reshape(1,-1)) - f(np.asarray(without_i).reshape(1,-1)) - indi_atts[feature_index_i] - indi_atts[feature_index_j]
                    #pair_atts[feature_index_i,feature_index_j] =  (k/n * perm_value/perms) - indi_atts[feature_index_i] - indi_atts[feature_index_j]
                    #pair_atts[feature_index_i,feature_index_j] =  (k/n * perm_value/perms) 
                    pair_atts[feature_index_i,feature_index_j] =  (k/n*(perm_value/perms)*1/coef) 
                    
                        
                    
                                 
    return(indi_atts,pair_atts)


In [34]:
atts = shap_taylor(np.asarray(x),np.asarray(z))
atts

[2, 3]
[2, 3]
[2]
[2, 3]
[2, 3]
[1]
[3]
[3]
[3]
[3]
[1]
[2]
[1, 2]
[2]
[2]
[0]
[0, 3]
[0]
[3, 0]
[3]
[0, 2]
[0]
[2, 0]
[2]
[2, 0]
[1]
[1]
[1, 0]
[0, 1]
[1]


({0: array([1]), 1: array([0]), 2: array([0]), 3: array([0])},
 {(0, 1): array([-0.13333333]),
  (0, 2): array([0.]),
  (0, 3): array([-0.03333333]),
  (1, 2): array([-0.1]),
  (1, 3): array([-0.13333333]),
  (2, 3): array([-0.16666667])})

In [626]:
def MSE():
    overall_s_error = []
    overall_ss_error = []
    overall_ks_error = []
    for i in range(0,1):
        x = [np.random.uniform(-1,1) for _ in range(0,7)]
        z = [np.random.uniform(-1,1) for _ in range(0,7)]
        ss_atts,seps,nonseps = RDG_interventional.RDG(f,list(x),list(z),[-1 for _ in range(0,len(x))],[1 for _ in range(0,len((x)))],0.1)
        s_atts = shapley.shapley_int(f,np.asarray(x),np.asarray(z))
        
        
        
        """datas = []
        for i in range(100):
            data = []
            for i in range(0,len(x)):
                data.append(random.uniform(-1,1))
            datas.append(data)
        datas = np.asarray(datas).reshape(100,len(x))
        explainer = shap.KernelExplainer(f, datas)
        shap_values = explainer.shap_values(np.asarray(x).reshape(1,len(x)), nsamples=1000)

        ks_atts = {}
        for i in range(0,len(x)):
            ks_atts[i] = shap_values[0][i]"""
            
        
      
        ground_truth = {}
        ground_truth[0] = 2*(x[0] * x[2] * x[3]) - 2*(z[0] * z[2] * z[3]) 
        ground_truth[1] =  (- 3*(x[1])**2) - ((- 3*(z[1])**2))
        ground_truth[2] = 2*(x[0] * x[2] * x[3]) - 2*(z[0] * z[2] * z[3])
        ground_truth[3] =  2*(x[0] * x[2] * x[3]) - 2*(z[0] * z[2] * z[3])
        ground_truth[4] = 4*(x[4] * x[5]) - 4*(z[4] * z[5])
        ground_truth[5] =  4*(x[4] * x[5]) - 4*(z[4] * z[5])
        ground_truth[6] =  (- (x[6])) - (- (z[6]))
        
        print(ss_atts)
        #print(ground_truth)

        ss_error = []
        for i in range(0,len(x)):
            u_index = 0
            for u in ss_atts.keys():
                if i in u:
                    ss_error.append(np.abs(ground_truth[i] - list(ss_atts.values())[u_index]))
                u_index +=1
        #print(np.mean(np.asarray(ss_error)))
        s_error = []
        for i in range(0,len(x)):
            u_index = 0
            for u in s_atts.keys():
                if i == u:
                    s_error.append(np.abs(ground_truth[i] - list(s_atts.values())[u_index]))
                u_index +=1
                
        """ks_error = []
        for i in range(0,len(x)):
            u_index = 0
            for u in ks_atts.keys():
                if i == u:
                    ks_error.append(np.abs(ground_truth[i] - list(ks_atts.values())[u_index]))
                u_index +=1"""
                
        #print(np.mean(np.asarray(s_error)))
        overall_s_error.append(s_error)
        overall_ss_error.append(ss_error)
        #overall_ks_error.append(ks_error)
    return(overall_s_error, overall_ss_error)



In [15]:
overall_s_error, overall_ss_error = MSE()

{(1,): array([0.02473234]), (6,): array([1.43673024]), (0, 2, 3): array([0.34348804]), (4, 5): array([-0.85591356])}


In [16]:
overall_s_error

[[array([0.29050357]),
  array([3.45556916e-15]),
  array([0.04545177]),
  array([0.35102075]),
  array([0.50283555]),
  array([1.3587491]),
  array([1.51656465e-13])]]

In [17]:
overall_ss_error

[[array([0.]),
  array([0.]),
  array([0.]),
  array([0.]),
  array([0.]),
  array([0.]),
  array([0.])]]